### ISSUE TITLE
debug_traceBlockByNumber block 4233910  -  "error": "execution timeout" 

### ISSUE THREAD

**Issue by iamredbull** [ericlee42/metis-replica-node#20]
Error on the debug_traceBlockByNumber  0x409ab6 (4233910) 
`{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x409ab6", {"tracer": "callTracer"}],"id":1}`
I also checked on a public node and there is also no way to get an answer

**Comment by ericlee42** [comment]
You should add timeout 

> timeout: STRING. Overrides the default timeout of 5 seconds for JavaScript-based tracing calls. https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug

**Comment by ericlee42** [comment]
the debug interface is not public for security

**Comment by iamredbull** [comment]
i have problem only with this block on my local node and on public node, on other blocks i get the correct answer
```
curl --location --request POST '127.0.0.1:8545' \
> --header 'Content-Type: application/json' \
> --data-raw '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x409ab6", {"tracer": "callTracer", "timeout": "1000s"}],"id":1}'
curl: (52) Empty reply from server
```

also in explorer not displayed transactions `https://andromeda-explorer.metis.io/block/4233910/transactions`

**Comment by iamredbull** [comment]
This response from public node on 4233911 block 
![image](https://user-images.githubusercontent.com/93740983/211309107-c7ac24db-f920-4ac8-9723-40416787cb8f.png)

**Comment by ericlee42** [comment]
the block's gas used is 100M, you can  try to increase resources for it.

**Comment by iamredbull** [comment]
I use powerfull host  CPU: AMD Ryzen 9 3900 12-Core Processor  Mem: 125Gi. Do you have any way to check if there is really a problem with the block or Metis client? 
I have 2 nodes deployed on powerful hosts and I have a problem with this block on 2 nodes. Also, the public node does not respond to this block either. @ericlee42

**Comment by ericlee42** [comment]
We have a new explorer in testing. it works fines

<img width="917" alt="image" src="https://user-images.githubusercontent.com/92196970/211317156-3fe24f30-ff45-45a4-828c-eeea04419d21.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/92196970/211317268-ae5621ec-d2c1-4656-8aab-ecdcde983587.png">

**Comment by iamredbull** [comment]
Сan you please share version dtl and metis l2 and what env you use start node?  @ericlee42

**Comment by ericlee42** [comment]
I don't think it's related to the versions, 

my node is deployed with aws c5.4xlarge.

it takes about 1 minutes to get the trace.

**Comment by ericlee42** [comment]
the env file is public in this repo.
