### ISSUE TITLE
Getting error while running the metis replica node.

### ISSUE THREAD

**Issue by AlgoTradingExpert** [ericlee42/metis-replica-node#21]
~/metis-replica-node # docker-compose logs --tail=10 dtl
Attaching to metis-replica-node_dtl_1
dtl_1     | {"level":50,"time":1677603660739,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:146:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:84:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:64:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:76:9"},"msg":"Caught an unhandled error"}
dtl_1     | {"level":30,"time":1677603660934,"fromBlock":4936145,"toBlock":4936146,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1677603666965,"fromBlock":4936146,"toBlock":4936147,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1677603667450,"fromBlock":4936147,"toBlock":4936152,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1677603667774,"fromBlock":4936152,"toBlock":4936153,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":50,"time":1677603667865,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:146:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:84:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:64:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:76:9"},"msg":"Caught an unhandled error"}
dtl_1     | {"level":30,"time":1677603668055,"fromBlock":4936152,"toBlock":4936153,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1677603709185,"fromBlock":4936153,"toBlock":4936154,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1677603709487,"fromBlock":4936154,"toBlock":4936155,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1677603724904,"fromBlock":4936155,"toBlock":4936156,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}

**Comment by ericlee42** [comment]
Please check that your eth rpc configuration is correct and that it is working properly

https://github.com/ericlee42/metis-replica-node#change-config
