### ISSUE TITLE
Failed to raise file descriptor allowance: operation not permitted

### ISSUE THREAD

**Issue by Fr1SeZ** [ericlee42/metis-replica-node#28]
After running docker compose up, the following error appears cyclically in the log.
![1](https://github.com/ericlee42/metis-replica-node/assets/93135119/dc3efd06-a844-4786-974c-c75c35f3264d)

In discord they suggested to me "I'd try to increase the file descriptor limit if possible", did not help.
from "cat /proc/sys/fs/file-max" i get  9223372036854775807
from "ulimit -Ha" i get  in open files "524288"

As far as I understand, it occurs when executing "geth init --datadir=/"$DATADIR" "$TEMP_DIR"/genesis.json" in geth.sh. Any ideas on how to solve this problem?

**Comment by ericlee42** [comment]
the screenshot linkage is broken.

**Comment by Fr1SeZ** [comment]
> ссылка на скриншот не работает.

thank, already solved
