### ISSUE TITLE
Node is in archive mode even if configuration has not been changed.

### ISSUE THREAD

**Issue by 0xSorcerer** [ericlee42/metis-replica-node#29]
I ran the docker container without making the changes needed to run an archive node, since I only need a full node.

After 3/4 hours of syncing, I am only at block 3M and the chaindata directory is already 72GB. I've done a further test by executing the following request:

`curl --data '{"method":"eth_getBalance","params":["0x1838Be1Ce335f3658072a1db6AD3A6b04629bF5C", "0x8"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`

Which queries for the balance of address `0x1838Be1Ce335f3658072a1db6AD3A6b04629bF5C`at block 8, where it receives 0.2 Metis. The requests goes through and it outputs the correct balance, indicating that the node is indeed syncing as archive.

How can I make it only a full node?

**Comment by ericlee42** [comment]
it has been fixed, you can use the latest commit.

if you want to switch to the full node completely, you have to delete the geth data first.

**Comment by 0xSorcerer** [comment]
I deleted the whole git clone folder and re-cloned. I am currently at block 100k but the aforementioned JSON-RPC request still goes through. Why is it still syncing as archive?
